"""Published fixtures. No model."""

PAYLOAD = "EXPLOIT:universal-cheat"
PATH = "/board/cheat"

CASES = {
    "board": {
        "id": "board",
        "title": "Shared board",
        "store_mode": "leaky",
        "sink_open": False,
        "horizon": 14,
        "partitions": False,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "copiers_sink": False,
    },
    "partition": {
        "id": "partition",
        "title": "Cut visibility",
        "store_mode": "partitioned",
        "sink_open": False,
        "horizon": 14,
        "partitions": True,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "copiers_sink": False,
    },
    "leaky": {
        "id": "leaky",
        "title": "Leaky index",
        "store_mode": "leaky",
        "sink_open": False,
        "horizon": 14,
        "partitions": True,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "copiers_sink": False,
    },
    "ash": {
        "id": "ash",
        "title": "Names wipe",
        "store_mode": "leaky",
        "sink_open": False,
        "horizon": 16,
        "partitions": False,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "scheduled_wipe": (8, "names"),
        "copiers_sink": False,
    },
    "sterile": {
        "id": "sterile",
        "title": "Full wipe",
        "store_mode": "leaky",
        "sink_open": False,
        "horizon": 16,
        "partitions": False,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "scheduled_wipe": (8, "all"),
        "copiers_sink": False,
    },
    "sink": {
        "id": "sink",
        "title": "Open sink",
        "store_mode": "leaky",
        "sink_open": True,
        "horizon": 14,
        "partitions": False,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "copiers_sink": True,
    },
    "probe": {
        "id": "probe",
        "title": "Probe PUT",
        "store_mode": "leaky",
        "sink_open": False,
        "horizon": 10,
        "partitions": False,
        "worker_count": 8,
        "index_at": 0,
        "payload": PAYLOAD,
        "put_path": PATH,
        "probe_at": 3,
        "copiers_sink": False,
    },
}


def get_case(id_: str) -> dict:
    return CASES[id_]
